### PR TITLE
New upstream snapshot.

### PR DESCRIPTION
**Pull request by smoser**
cloud-utils (0.31-22-g37d4e32a-0ubuntu1) groovy; urgency=medium

  * New upstream snapshot.
    - Growpart fix undefined variable in growpart error message.
    - Add test for growpart lvm resize.
    - Growpart: add support for resizing an lvm pv after growing the
      partition. ([LP: #1799953](https://bugs.launchpad.net/bugs/1799953))
    - Make resize functions return, so unlock_disk_and_settle is called.
    - CI: rename the "tip" tox environments to tip-* [Paride Legovini]
    - CI: pin the shellcheck version and add a shellcheck-tip environment
      [Paride Legovini]
    - CI: make shellcheck check tools/* [Paride Legovini]
    - IMDSv2 session token support (#1) [Paride Legovini] ([LP: #1870244](https://bugs.launchpad.net/bugs/1870244))
    - growpart: parse the kernel version in a more robust way (#2)
      [Paride Legovini] ([LP: #1881014](https://bugs.launchpad.net/bugs/1881014))
    - Fix some pylint, flake8, shellcheck issues and add basic CI (#4)
      [Paride Legovini]

 -- Scott Moser <smoser@ubuntu.com>  Tue, 21 Jul 2020 09:39:36 -0400

### CODE REVIEW

**Comment by raharper** [comment]
@smoser  which new-upstream-snapshot are you using? Did you manually redact your name from the changelog?  Otherwise, the diff for the snapshot looks good to me.

```
(crispyboi) cloud-utils % ~/work/git/uss-tableflip/scripts/new-upstream-snapshot
updating remote upstream for default commitish upstream/master.
X11 forwarding request failed on channel 0
diff --git a/debian/changelog b/debian/changelog
index 7534795..dba78c9 100644
--- a/debian/changelog
+++ b/debian/changelog
@@ -1,3 +1,24 @@
+cloud-utils (0.31-22-g37d4e32a-0ubuntu1) UNRELEASED; urgency=medium
+
+  * New upstream snapshot.
+    - Growpart fix undefined variable in growpart error message. [Scott Moser]
+    - Add test for growpart lvm resize. [Scott Moser]
+    - Growpart: add support for resizing an lvm pv after growing the
+      partition. [Scott Moser] (LP: #1799953)
+    - Make resize functions return, so unlock_disk_and_settle is called.
+      [Scott Moser]
+    - CI: rename the "tip" tox environments to tip-* [Paride Legovini]
+    - CI: pin the shellcheck version and add a shellcheck-tip environment
+      [Paride Legovini]
+    - CI: make shellcheck check tools/* [Paride Legovini]
+    - IMDSv2 session token support (#1) [Paride Legovini] (LP: #1870244)
+    - growpart: parse the kernel version in a more robust way (#2)
+      [Paride Legovini] (LP: #1881014)
+    - Fix some pylint, flake8, shellcheck issues and add basic CI (#4)
+      [Paride Legovini]
+
+ -- Ryan Harper <rharper@woxford.com>  Tue, 21 Jul 2020 09:19:33 -0500
+
 cloud-utils (0.31-12-g3d6d5128-0ubuntu1) groovy; urgency=medium

   * New upstream snapshot.
Commit this change? (Y/n): y
[ubuntu/devel ec4a172] update changelog (New upstream snapshot 0.31-22-g37d4e32a).
 1 file changed, 21 insertions(+)
wrote new-upstream-changes.txt for cloud-utils version 0.31-22-g37d4e32a-0ubuntu1.
release with:
sed -i -e "1s/UNRELEASED/groovy/" debian/changelog
git commit -m "releasing cloud-utils version 0.31-22-g37d4e32a-0ubuntu1" debian/changelog
git tag ubuntu/0.31-22-g37d4e32a-0ubuntu1
# optionally push your tag: git push <remote> ubuntu/0.31-22-g37d4e32a-0ubuntu1
(crispyboi) cloud-utils % sed -i -e "1s/UNRELEASED/groovy/" debian/changelog
(crispyboi) cloud-utils % git commit -m "releasing cloud-utils version 0.31-22-g37d4e32a-0ubuntu1" debian/changelog
[ubuntu/devel a13bb4f] releasing cloud-utils version 0.31-22-g37d4e32a-0ubuntu1
 1 file changed, 1 insertion(+), 1 deletion(-)
(crispyboi) cloud-utils % git remote add smoser-github git@github.com:smoser/cloud-utils.git
(crispyboi) cloud-utils % git fetch smoser-github
X11 forwarding request failed on channel 0
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 27 (delta 19), reused 24 (delta 16), pack-reused 0
Unpacking objects: 100% (27/27), 3.53 KiB | 722.00 KiB/s, done.
From github.com:smoser/cloud-utils
 * [new branch]      cleanup/whitespace-cleanups       -> smoser-github/cleanup/whitespace-cleanups
 * [new branch]      feature/1799953-lvm-support       -> smoser-github/feature/1799953-lvm-support
 * [new branch]      master                            -> smoser-github/master
 * [new branch]      ubuntu/devel                      -> smoser-github/ubuntu/devel
 * [new tag]         ubuntu/0.31-22-g37d4e32a-0ubuntu1 -> ubuntu/0.31-22-g37d4e32a-0ubuntu1
(crispyboi) cloud-utils % git diff smoser-github/ubuntu/devel HEAD
diff --git a/debian/changelog b/debian/changelog
index 47aa131..c3658a9 100644
--- a/debian/changelog
+++ b/debian/changelog
@@ -1,11 +1,12 @@
 cloud-utils (0.31-22-g37d4e32a-0ubuntu1) groovy; urgency=medium

   * New upstream snapshot.
-    - Growpart fix undefined variable in growpart error message.
-    - Add test for growpart lvm resize.
+    - Growpart fix undefined variable in growpart error message. [Scott Moser]
+    - Add test for growpart lvm resize. [Scott Moser]
     - Growpart: add support for resizing an lvm pv after growing the
-      partition. (LP: #1799953)
+      partition. [Scott Moser] (LP: #1799953)
     - Make resize functions return, so unlock_disk_and_settle is called.
+      [Scott Moser]
     - CI: rename the "tip" tox environments to tip-* [Paride Legovini]
     - CI: pin the shellcheck version and add a shellcheck-tip environment
       [Paride Legovini]
@@ -16,7 +17,7 @@ cloud-utils (0.31-22-g37d4e32a-0ubuntu1) groovy; urgency=medium
     - Fix some pylint, flake8, shellcheck issues and add basic CI (#4)
       [Paride Legovini]

- -- Scott Moser <smoser@ubuntu.com>  Tue, 21 Jul 2020 09:39:36 -0400
+ -- Ryan Harper <rharper@woxford.com>  Tue, 21 Jul 2020 09:19:33 -0500

 cloud-utils (0.31-12-g3d6d5128-0ubuntu1) groovy; urgency=medium
```

**Comment by smoser** [comment]
@raharper yes. I manually removed my name from the changelog lines.
2 reasons for doing so:
a.) Its at least common-ish convention to do only give credit in individual changelog entries to people other than the uploader.
b.) I don't think i need my name on all lines anyway.   My basic policy has been to give credit / call out those who are not common contributors.

**Comment by smoser** [comment]
@

> There are some lintian warning that would be nice to fix:
> 
> ```
> W: cloud-utils source: ancient-python-version-field XS-Python-Version 2.6
> W: cloud-utils source: ancient-standards-version 3.9.8 (released 2016-04-06) (current is 4.5.0)
> W: cloud-utils source: package-uses-deprecated-debhelper-compat-version 7
> W: cloud-guest-utils: priority-extra-is-replaced-by-priority-optional
> W: cloud-image-utils: priority-extra-is-replaced-by-priority-optional
> W: cloud-utils: priority-extra-is-replaced-by-priority-optional
> ```
> 
> but it's fine for the moment. I'll submit a PR fixing them in master.
> 
> I just have a question before approving: should we bump the package version to at least 0.32? The package comes with new functionalities after all.

We can do a new upstream release for sure. That process would follow the cloud-init one (release tarball, changelog, new release on launchpad ...) and/or doing "release things" on github.

Thats an upstream decision, this is "just" packaging.  For ubuntu, I tend to think that "a rose by any other name would smell as sweet" (0.31-22-g37d4e32a is no better or worse than 0.32).  But I do think debian and other distros are more likely to pick up a 0.32.

I'm not opposed to an upstream release.  Someone just then need to do all the steps for doing one.

**Comment by smoser** [comment]
Subject: [ubuntu/groovy-proposed] cloud-utils 0.31-22-g37d4e32a-0ubuntu1 (Accepted)
Date: Tue, 21 Jul 2020 15:11:17 -0000

**Pull request merged**
