### PR TITLE
Drop the debian/ packaging directory from master

### PR DESCRIPTION
**Pull request by paride**
The Ubuntu packaging lives in the ubuntu/devel or ubuntu/<RELEASE>
branches. Not having a debian/ directory in master avoids confusion and
makes packaging easier for other Debian based distribution (or Debian
itself) where a debian/ directory in the upstream source tree conflicts
with the directory containing the packaging for that distribution.

### CODE REVIEW

**Comment by paride** [comment]
@raharper did the past few uploads, I'd be interested in his take :)

**Comment by paride** [comment]
@blackboxsw pointed out that having `debian/` in master makes it easy to have daily builds from master. That's true, but the same can be achieved with a recipe like:
```
# git-build-recipe format 0.4 deb-version {latest-tag}+{revtime}-g{git-commit}-0ubuntu1
lp:cloud-utils master
nest-part packaging lp:cloud-utils debian debian ubuntu/devel
```
which copies the `debian` directory of branch `ubuntu/devel` of the `lp:cloud-utils` repo in the main recipe branch (`lp:cloud-utils master`), the target directory being named again `debian`.

**Comment by raharper** [comment]
The other use-case is building a deb within master;  So we'd need changes to tools/build-deb tools/make-tarball to handle pulling in ubuntu/devel.

This isn't trivial as one needs to over lay two tarbals (one from git origin/master and one from origin/ubuntu/devel);  I played a bit with git archive --format=tar to extract just the debian dir, but I couldn't quite get it right.

An alternative would be to make a branch of HEAD and merge in ubuntu/devel; then use make-tarball on the temp dir.

**Comment by smoser** [comment]
I'd leave debian/ in master.
its easy packaging it makes it easy to build. and easy enough to merge.

**Comment by paride** [comment]
I see your points. Let me think about it a bit more, and if I can't find anything smarter I'll just close this PR.

**Comment by smoser** [comment]
@raharper wrt "build with debian packaging from other branch", I recently put some work into 'build-upstream-pkg' tool at https://gist.github.com/smoser/d3dbf2b8a073675e0700472e12513e0a .

It kind of works, and uses git-archive and such.

**Comment by raharper** [comment]
@smoser  Neat; I don't see use of git archive (looks like it uses worktree + tar)  ...   I played around with git archive in cloud-init like so.  There's no exclude in git archive so the tarball is slightly bloated.

```
# base tarball with eveyrthing from git
git archive --format=tar --prefix="$archive_base/" "$rev" > "$tar"
# include the release branch debian/ dir if specified                          
if [ -n "$release" ]; then                                                     
    reltar="$TEMP_D/${release}.tar"                                            
    git archive --format=tar --prefix="$archive_base/debian/" origin/ubuntu/$release:debian > "$reltar"
    tar --concatenate --file="$tar" "$reltar"                                  
fi                                                                             
gzip -9 -c "$tar" > "$output" 
```

**Comment by paride** [comment]
I played with git a bit and came out with this scripts:

https://gist.github.com/paride/82db2b02b53f72dd94808c39f023b191 (`build-deb-prepare`)
https://gist.github.com/paride/0b1a4d2556452bcbe68bbd82e1cd904b (`build-deb`)

`build-deb-prepare` prepares the current branch for building a .deb by pulling `debian/` from a packaging branch (via `git restore`), updating `d/changlog` using `git describe` and generates the `.orig` tarball with `git deborig` (a wrapper around `git archive`, part of `devscripts`). The package can at this point is a standard debian source tree and can be manually built with `debuild` or `dpkg-buildpackage`.

`build-deb` calls `build-deb-prepare` and then builds the package using `debuild`, all in a temporary working tree built using `git worktree`. The main worktree can't be easily used because files in `.gitignore` are not included in the `.orig` tarball, but the `dpkg-*` tools will find them in the working tree complain about the diff. The untracker files could be stashed using `git stash --all` and then popped, but I think it's better not to tamper with the active working tree too much. A secondary, temporary working tree is perfect for the purpose. This is similar to @smoser's `build-upstream-pkg`.

I kind of like this solution more than having a `debian/` directory in master for a few reasons:
- It's one less thing to maintain and keep in sync.
- It's nicer not to have a packaging directory in the upstream tree
- Even with `debian/` in `master` building the package require special tools.

However I have no strong feelings on this. There's also a matter of uniformity between the projects. Should you not find my solution better than the current one I'll not insist more and perhaps submit `build-deb-prepare` for inclusion in the `uss-tableflip` repo :)

**Comment by smoser** [comment]
The reason for having debian/ in upstream is that changes in upstream require changes in packaging.
Acknowledging that means that 'git merge' or 'git cherry-pick' do the right thing.  Ignoring it means that you have to remember or find out later "oh yeah, we made that upstream change and now we have to change packaging".

The debian directory is not "one more thing to keep in sync" any more than any other directory (or file) is "one more thing to keep in sync".   Generally speaking, git does a really good job.

I completely agree with debian/changelog being a pita on merge. thats why it is not here.

**Comment by paride** [comment]
I've been clearly wearing the package maintainer hat more often than the upstream developer one.

Closing this PR, thanks for the thoughtful discussion.

**Pull request closed without merging**
