### PR TITLE
growpart: adding LANG=C before the command sfdisk --version

### PR DESCRIPTION
**Pull request by xiachen-rh**
Fix issue LP: #1928167 growpart doesn't work when LANG=cs_CZ.UTF-8

### CODE REVIEW

**Review by paride — CHANGES_REQUESTED** [review]
Hi, this LGTM, could you please just amend the commit message referring to the Launchpad as `LP: #1928167" instead of using the full launchpad URL? This will help tracking fixed bugs when generating changelogs. Thanks!

**Comment by xiachen-rh** [comment]
> Hi, this LGTM, could you please just amend the commit message referring to the Launchpad as `LP: #1928167" instead of using the full launchpad URL? This will help tracking fixed bugs when generating changelogs. Thanks!

Hi Paride, 
thanks for your review. I changed the commit message, is it OK now? I don't have much experience of upstream contribution, so let me know if any problem, and I will follow the rule.
thanks,
Amy

**Comment by paride** [comment]
Hey @xiachen-rh, you changed the GitHub PR title, but not the actual commit message. For that you'll have to do something like:
```
$ git commit --amend # (from the tip of your branch)
$ git push --force # to update the branch on github
```

**Comment by xiachen-rh** [comment]
> Hey @xiachen-rh, you changed the GitHub PR title, but not the actual commit message. For that you'll have to do something like:
> 
> ```
> $ git commit --amend # (from the tip of your branch)
> $ git push --force # to update the branch on github
> ```

Hi Paride,
My first commit was submitted via web UI on my master branch, but I didn't find the "amend" button, so I run the git command as you told me, it created a new commit [bc3cfec](https://github.com/canonical/cloud-utils/commit/bc3cfecbe192bb64277b087d1a08a40f51abf7ac), is it OK? 

thanks,
Amy

**Review by paride — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
